
site_name: ARCHIMEDES User Support Documentation

theme:
  name: material
  logo: images/archimedes_icon.png
  features:
    - navigation.tabs
    - navigation.top

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/open-links-new-tab.js
  
markdown_extensions:
  - attr_list

plugins:
  - search
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true

        - locale: fr
          name: Français
          build: true
          site_name: Guide d'utilisation d'ARCHIMEDES
          nav_translations:
            Home: Accueil
            Data Contribution: Partage de données
            Getting started: Démarrer
            Establish a Data Contribution Agreement (DCA): Établir un accord de contribution de données (DCA)
            Account Creation: Création d'un compte
            Create a new project and contribute data: Créer un nouveau projet et partager des données
            Portal Navigation: Portail
            Data Transfer: Transfert de données
            Data Access: Accès aux données
            Data Search: Recherche de données
            Analytical Tools: Outils analytiques
            Data Curation: Curation
            Data Release: Diffusion des données

nav:
  - Home: index.md

  - Data Contribution: 
      - Getting started: getting-started.md
      - Establish a Data Contribution Agreement (DCA): dca.md
      - Account Creation: account-creation.md
      - Create a new project and contribute data: create-project.md

  - Portal Navigation: data-portal.md
  - Data Transfer: transferring-data.md
  - Data Access: data-access.md
  - Data Search: search-data.md
  - Analytical Tools: processing-tools.md
  - Data Curation: data-curation.md
  - Data Release: data-release.md
